include: package:flutter_lints/flutter.yaml

linter:
  rules:
    always_declare_return_types: true
    avoid_print: false
    directives_ordering: true
    omit_local_variable_types: true
    prefer_const_constructors_in_immutables: true
    prefer_const_constructors: true
    prefer_const_declarations: true
    prefer_const_literals_to_create_immutables: true
    prefer_final_fields: true
    prefer_final_locals: true
    prefer_relative_imports: true
    prefer_single_quotes: true
    require_trailing_commas: true
    sort_constructors_first: true
    sort_pub_dependencies: true
    sort_unnamed_constructors_first: true
    unnecessary_const: true
    use_key_in_widget_constructors: true
    unawaited_futures: true
    await_only_futures: true
    prefer_final_in_for_each: true
    avoid_types_on_closure_parameters: true
