name: flutter_cblite_userprofile_sync
description: Couchbase Lite Flutter Demo
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.18.4 <3.0.0'

dependencies:
  archive: ^3.3.2
  cbl: ^2.1.1
  cbl_flutter: ^2.0.2
  cbl_flutter_ee: ^2.1.2
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  image_picker: ^0.8.6
  path: ^1.8.2
  path_provider: ^2.0.11

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/
